# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './leonardo_ai/view/model_search_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelSearchItem(object):
    def setupUi(self, ModelSearchItem):
        ModelSearchItem.setObjectName("ModelSearchItem")
        ModelSearchItem.resize(250, 132)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModelSearchItem)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(ModelSearchItem)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblImage = QtWidgets.QLabel(self.frame_2)
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout_2.addWidget(self.lblImage)
        self.lblName = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblName.setFont(font)
        self.lblName.setWordWrap(True)
        self.lblName.setObjectName("lblName")
        self.verticalLayout_2.addWidget(self.lblName)
        self.lblDescription = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescription.sizePolicy().hasHeightForWidth())
        self.lblDescription.setSizePolicy(sizePolicy)
        self.lblDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescription.setWordWrap(True)
        self.lblDescription.setObjectName("lblDescription")
        self.verticalLayout_2.addWidget(self.lblDescription)
        self.lblUser = QtWidgets.QLabel(self.frame_2)
        self.lblUser.setObjectName("lblUser")
        self.verticalLayout_2.addWidget(self.lblUser)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(ModelSearchItem)
        QtCore.QMetaObject.connectSlotsByName(ModelSearchItem)

    def retranslateUi(self, ModelSearchItem):
        _translate = QtCore.QCoreApplication.translate
        ModelSearchItem.setWindowTitle(_translate("ModelSearchItem", "Form"))
        self.lblName.setText(_translate("ModelSearchItem", "Vintage Style Photography"))
        self.lblDescription.setText(_translate("ModelSearchItem", "A versatile model that excels at realism and photography. Better results with longer prompts."))
        self.lblUser.setText(_translate("ModelSearchItem", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModelSearchItem = QtWidgets.QWidget()
    ui = Ui_ModelSearchItem()
    ui.setupUi(ModelSearchItem)
    ModelSearchItem.show()
    sys.exit(app.exec_())
