# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './leonardo_ai/view/model_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modelItem(object):
    def setupUi(self, modelItem):
        modelItem.setObjectName("modelItem")
        modelItem.resize(400, 64)
        modelItem.setMinimumSize(QtCore.QSize(0, 64))
        self.horizontalLayout = QtWidgets.QHBoxLayout(modelItem)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gfxIcon = QtWidgets.QLabel(modelItem)
        self.gfxIcon.setMaximumSize(QtCore.QSize(64, 64))
        self.gfxIcon.setObjectName("gfxIcon")
        self.horizontalLayout.addWidget(self.gfxIcon)
        self.frame = QtWidgets.QFrame(modelItem)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblBase = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBase.setFont(font)
        self.lblBase.setObjectName("lblBase")
        self.gridLayout.addWidget(self.lblBase, 0, 0, 1, 1)
        self.lblModelDim = QtWidgets.QLabel(self.frame)
        self.lblModelDim.setObjectName("lblModelDim")
        self.gridLayout.addWidget(self.lblModelDim, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(modelItem)
        QtCore.QMetaObject.connectSlotsByName(modelItem)

    def retranslateUi(self, modelItem):
        _translate = QtCore.QCoreApplication.translate
        modelItem.setWindowTitle(_translate("modelItem", "Form"))
        self.gfxIcon.setText(_translate("modelItem", "TextLabel"))
        self.lblName.setText(_translate("modelItem", "Leonardo Vision XL"))
        self.lblBase.setText(_translate("modelItem", "SL_21"))
        self.lblModelDim.setText(_translate("modelItem", "1024x768"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modelItem = QtWidgets.QWidget()
    ui = Ui_modelItem()
    ui.setupUi(modelItem)
    modelItem.show()
    sys.exit(app.exec_())
