# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './leonardo_ai/view/model_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modelItem(object):
    def setupUi(self, modelItem):
        modelItem.setObjectName("modelItem")
        modelItem.resize(300, 64)
        modelItem.setMinimumSize(QtCore.QSize(0, 64))
        modelItem.setMaximumSize(QtCore.QSize(300, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(modelItem)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gfxIcon = QtWidgets.QLabel(modelItem)
        self.gfxIcon.setMaximumSize(QtCore.QSize(64, 64))
        self.gfxIcon.setText("")
        self.gfxIcon.setObjectName("gfxIcon")
        self.horizontalLayout.addWidget(self.gfxIcon)
        self.frame = QtWidgets.QFrame(modelItem)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 64))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblBase = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBase.setFont(font)
        self.lblBase.setObjectName("lblBase")
        self.horizontalLayout_2.addWidget(self.lblBase, 0, QtCore.Qt.AlignLeft)
        self.lblModelDim = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblModelDim.setFont(font)
        self.lblModelDim.setObjectName("lblModelDim")
        self.horizontalLayout_2.addWidget(self.lblModelDim, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.lblName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.verticalLayout.addWidget(self.lblName)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(modelItem)
        QtCore.QMetaObject.connectSlotsByName(modelItem)

    def retranslateUi(self, modelItem):
        _translate = QtCore.QCoreApplication.translate
        modelItem.setWindowTitle(_translate("modelItem", "Form"))
        self.lblBase.setText(_translate("modelItem", "SL_21"))
        self.lblModelDim.setText(_translate("modelItem", "1024x768"))
        self.lblName.setText(_translate("modelItem", "Vintage Style Photography"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modelItem = QtWidgets.QWidget()
    ui = Ui_modelItem()
    ui.setupUi(modelItem)
    modelItem.show()
    sys.exit(app.exec_())
